POST http://127.0.0.1:8000/api/users/signup
Content-Type: application/json

{ "username": "notguide3", "password": "a", "email": "nguidee@mail.com", "cpf":"12345617110", "is_guide": "False"}

###
POST http://127.0.0.1:8000/api/users/signup
Content-Type: application/json

{ "username": "guide", "password": "a", "email": "guide@mail.com", "cpf":"12345618911", "is_guide": "True"}

###

GET http://127.0.0.1:8000/api/users/
Content-Type: application/json

###

POST http://127.0.0.1:8000/api/users/login
Content-Type: application/json

{ "username": "guide", "password": "a"}
###

POST http://127.0.0.1:8000/api/users/login
Content-Type: application/json

{ "username": "juba", "password": "vfde2323"}

###

# POST http://127.0.0.1:8000/api/users/login
# Content-Type: application/json

# { "username": "juba", "password": "vfde2323"}

###

POST http://127.0.0.1:8000/api/users/logout 
Content-Type: application/json
Authorization: token 44f0ab236f925dfeb18f60a92391c082c8cfd513


# Requisição cadastro ecoturista
# POST http://127.0.0.1:8000/user/signup/ 
# Content-Type: application/json

# { "username": "turista",
#   "email": "turista@mail.com", 
#   "cpf":"12345678990",
#   "password": "turista",
#   "telefone": "123456789"}

###
POST http://127.0.0.1:8000/api/trips/
Content-Type: application/json
Authorization: token c4938ff0f7a120be65decd0d573e8aa9db0bcd4c


{ "title": "Viagem",
    "description": "Viagem uau",
    "date": "2025-01-29",
    "location": "Recife",
    "max_participants": 5,
    "price": 8.0,
    "category": "trilha",
    "guide": 4}

###

PATCH http://127.0.0.1:8000/api/trips/1/
Authorization: Token a91ba61d4d14f22be41509246ae75c4eb4b508a2
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="greenpeace.jpg"
Content-Type: image/jpeg

< C:\Users\mhmon\Desktop\imgs\greenpeace.jpg
--boundary--
###

PATCH http://127.0.0.1:8000/api/trips/1/
Authorization: Token a91ba61d4d14f22be41509246ae75c4eb4b508a2
Content-Type: application/json

{ "title": "Viagem2",
    "description": "Viagem uau",
    "date": "2025-01-29",
    "location": "Recife",
    "max_participants": 5,
    "price": 2.0}




###

# PATCH http://127.0.0.1:8000/api/trips/2/
# Content-Type: multipart/form-data; boundary=boundary

# --boundary
# Content-Disposition: form-data; name="photo"; filename="Screenshot_2025-01-15_140318.jpg"
# Content-Type: image/jpg
# C:\Users\mhmon\Desktop\imgs\1200px-Rainforest.jpg
# --boundary--

###

GET http://127.0.0.1:8000/api/get_trips/
Content-Type: application/json

###
POST http://127.0.0.1:8000/api/users/login
Content-Type: application/json

{ "username": "notguide", "password": "a"}

###
POST http://127.0.0.1:8000/api/trips/register_for_trip/
Content-Type: application/json
Authorization: token 920e38e86dd125d51fdcad4bb9272fb478d2ffc7

{ "id_viagem": 2}
###
# Requisição para pegar id de preferencias multipla escolha

GET  http://127.0.0.1:8000/api/users/category_preferences
Content-Type: application/json

###
POST  http://127.0.0.1:8000/api/users/preferences 
Content-Type: application/json
Authorization: token c4938ff0f7a120be65decd0d573e8aa9db0bcd4c

{ "genero": "Outro",
  "faixa_etaria": "25-34",
  "pais_regiao": "Brasil",
  "estilo_ecotrip": [2,2],
  "prefere_viajar_com": [3,4],
  "viagens_anuais": "3-5",
  "orcamento_medio": "$",
  "prioridade_viagem": [5,6],
  "importancia_sustentabilidade": 1,
  "pagaria_por_servicos_sustentaveis": "Sim, sem problemas!",
  "participa_ecoturismo": "Sim, frequentemente"
}

###
