# Generated by Django 5.1.5 on 2025-01-29 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='trips_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
