# Generated by Django 5.1.5 on 2025-02-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('trilha', 'Trilhas e Caminhadas'), ('passaro', 'Observação de Pássaros'), ('aqua', 'Aqua Trekking'), ('ecodiving', 'Eco-Diving'), ('arborismo', 'Arborismo'), ('cavalo', 'Passeios a Cavalo'), ('canoa', 'Canoagem e Caiaque'), ('ciclismo', 'Ciclismo de Montanha')], max_length=100),
        ),
    ]
