# Generated by Django 5.1.5 on 2025-02-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='category',
            field=models.CharField(choices=[('trilha', 'Trilha'), ('sustentável', 'Sustentável')], max_length=100),
        ),
    ]
