# Generated by Django 5.1.5 on 2025-03-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('trilha', 'Trilhas e Caminhadas'), ('passaro', 'Observação de Pássaros'), ('aqua', 'Aqua Trekking'), ('ecodiving', 'Eco-Diving'), ('arborismo', 'Arborismo'), ('cavalo', 'Passeios a Cavalo'), ('canoa', 'Canoagem e Caiaque'), ('ciclismo', 'Ciclismo de Montanha')], max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.AddField(
            model_name='trip',
            name='category',
            field=models.ManyToManyField(related_name='trips', to='trips.category'),
        ),
    ]
