# Generated by Django 5.1.5 on 2025-02-02 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_category'),
        ('trips', '0002_trip_participants'),
    ]

    operations = [
    ]
