# Generated by Django 5.1.5 on 2025-03-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_category_remove_trip_category_trip_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('style', models.CharField(choices=[('trilha', 'Trilhas e Caminhadas'), ('passaro', 'Observação de Pássaros'), ('aqua', 'Aqua Trekking'), ('ecodiving', 'Eco-Diving'), ('arborismo', 'Arborismo'), ('cavalo', 'Passeios a Cavalo'), ('canoa', 'Canoagem e Caiaque'), ('ciclismo', 'Ciclismo de Montanha')], max_length=50)),
                ('priority', models.CharField(choices=[('sozinho', 'Sozinho'), ('familia', 'Em Família'), ('amigos', 'Com Amigos'), ('casal', 'Em Casal')], max_length=50)),
                ('category', models.CharField(choices=[('ecotrip_style', 'Estilo Ecotrip'), ('travel_priority', 'Prioridade de Viagem')], max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='category',
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_tags',
            field=models.ManyToManyField(related_name='trips', to='trips.triptags'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
