# Generated by Django 5.1.5 on 2025-02-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_merge_0002_alter_trip_category_0002_trip_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='photo',
            field=models.ImageField(null=True, upload_to='trips/'),
        ),
    ]
