# Generated by Django 5.1.5 on 2025-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_triptags_remove_trip_category_trip_trip_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('ecotrip_style', 'Estilo Ecotrip'), ('ecotrip_companion', 'Companheiro de Viagem')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='trip_tags',
        ),
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='trips', to='trips.triptag'),
        ),
        migrations.DeleteModel(
            name='TripTags',
        ),
    ]
