# Generated by Django 5.1.5 on 2025-03-02 18:37

from django.db import migrations

from django.db import migrations

def populate_tags(apps, schema_editor):
    from trips.models import TripTag
    
    categories = {
        'ecotrip_style': [
            ('trilha', 'Trilhas e Caminhadas'),
            ('passaro', 'Observação de Pássaros'),
            ('aqua', 'Aqua Trekking'),
            ('ecodiving', 'Eco-Diving'),
            ('arborismo', 'Arborismo'),
            ('cavalo', 'Passeios a Cavalo'),
            ('canoa', 'Canoagem e Caiaque'),
            ('ciclismo', 'Ciclismo de Montanha'),
        ],
        'travel_companion': [
            ('sozinho', 'Sozinho'),
            ('familia', 'Em Família'),
            ('amigos', 'Com Amigos'),
            ('casal', 'Em Casal'),
        ]
    }

    for category, tags in categories.items():
        for tag_code, tag_name in tags:
            TripTag.objects.get_or_create(name=tag_code, category=category)

class Migration(migrations.Migration):
    dependencies = [
        ('trips', '0005_tagcategory_triptag_remove_trip_trip_tags_trip_tags_and_more'),  # Coloque a migração anterior aqui
    ]

    operations = [
        migrations.RunPython(populate_tags),
    ]


