# Generated by Django 5.1.5 on 2025-03-02 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_auto_20250302_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagCategory',
        ),
    ]
