###
# Cadastro de avaliação (Necessário passar token do user logado, user deve estar na viagem avaliada)
POST http://127.0.0.1:8000/api/reviews/create_review/
Content-Type: application/json
Authorization: token 461a5e09cc0bdc99446afff880d4daf357b76c64

{ "trip_id": 1,"comment": "passeio legal sla","stars": 2}

###
# Edição de avaliação (Necessário passar token do user logado)
DELETE http://127.0.0.1:8000/api/reviews/edit_review/2/
Content-Type: application/json
Authorization: token 461a5e09cc0bdc99446afff880d4daf357b76c64

###
# Cadastro de passeio (Necessário passar token do guia logado)
POST http://127.0.0.1:8000/api/trips/
Content-Type: application/json
Authorization: token bb536087159b5c6721f0376868b2e4e54d45b8f0


{ "title": "Passeio Muito Legal!!!!!!",
    "description": "arvore e mais coisa",
    "date": "2025-01-29",
    "location": "Recife",
    "max_participants": 5,
    "price": 8.0,
    "tags": [1,2,3]}

###

# Requisição para editar foto da viagem
PATCH http://127.0.0.1:8000/api/trips/1/
Authorization: Token a91ba61d4d14f22be41509246ae75c4eb4b508a2
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="photo"; filename="greenpeace.jpg"
Content-Type: image/jpeg

< C:\Users\mhmon\Desktop\imgs\greenpeace.jpg
--boundary--
###

# Edição de viagem
PATCH http://127.0.0.1:8000/api/trips/1/
Authorization: Token a91ba61d4d14f22be41509246ae75c4eb4b508a2
Content-Type: application/json

{ "title": "Viagem2",
    "description": "Viagem uau",
    "date": "2025-01-29",
    "location": "Recife",
    "max_participants": 5,
    "price": 2.0}

###

# Recuperar todas as viagens cadastradas
GET http://127.0.0.1:8000/api/get_trips/
Content-Type: application/json


###

# Cadastrar em viagem (Usuário padrão)
POST http://127.0.0.1:8000/api/trips/register_for_trip/
Content-Type: application/json
Authorization: token e2adc6778acd6aff5c2c3d3b7c4ac3e0a087823e

{ "id_viagem": 1}



###
# Requisição para pegar id de preferencias multipla escolha
GET  http://127.0.0.1:8000/api/category_preferences
Content-Type: application/json

###
# Ordenar por maior preço
GET http://127.0.0.1:8000/api/get_trips/?ordering=-price 
Content-Type: application/json



###
# Buscar trips com filtros aplicados (cidade, estilo, faixa de preço, pesquisa no título e ordenação)
GET http://127.0.0.1:8000/api/get_trips/?city=Recife&style=aqua&price_range=$&search=Passeio&ordering=-price
Content-Type: application/json

###
# Buscar trips pelo inicio do nome
GET http://127.0.0.1:8000/api/get_trips/?search=Trilha
Content-Type: application/json

###
# Buscar trips com filtros (cidade, estilo, faixa de preço, ordenação)
GET http://127.0.0.1:8000/api/get_trips/?city=Recife&style=passaro&price_range=$&ordering=-price
Content-Type: application/json

# Estilo Ecotrip está mapeado desta maneira:
'''
'ecotrip_style': [
            ('passaro', 'Observação de Pássaros'),
            ('aqua', 'Aqua Trekking'),
            ('trilha', 'Trilhas e Caminhadas'),
            ('ecodiving', 'Eco-Diving'),
            ('arborismo', 'Arborismo'),
            ('cavalo', 'Passeios a Cavalo'),
            ('canoa', 'Canoagem e Caiaque'),
            ('ciclismo', 'Ciclismo de Montanha'),
        ],

'''