# Generated by Django 5.1.5 on 2025-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencecategory',
            name='category',
            field=models.CharField(choices=[('ecotrip_style', 'Estilo Ecotrip'), ('travel_companion', 'Companheiro de Viagem'), ('travel_priority', 'Prioridade de Viagem')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='importancia_sustentabilidade',
            field=models.CharField(blank=True, choices=[(1, 'Muito importante'), (2, 'Importante'), (3, 'Pouco importante'), (4, 'Nada importante')], max_length=20, null=True),
        ),
    ]
