# Generated by Django 5.1.5 on 2025-01-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customuser_experiencia_customuser_formacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_tourist',
        ),
    ]
