# Generated by Django 5.1.5 on 2025-02-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_customuser_cpf'),
        ('user_app', '0002_preferencecategory_category_and_more'),
    ]

    operations = [
    ]
