# Generated by Django 5.1.5 on 2025-01-24 21:25

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_customuser_is_tourist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experiencia',
        ),
        migrations.AddField(
            model_name='customuser',
            name='endereco',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='EcoGuide',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('especialidade', models.CharField(choices=[('floresta', 'Floresta'), ('cachoeira', 'Cachoeira')], max_length=15)),
                ('formacao', models.CharField(blank=True, max_length=15, null=True)),
                ('licenca', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('user_app.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
