# Generated by Django 5.1.5 on 2025-02-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_merge_20250219_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='importancia_sustentabilidade',
            field=models.CharField(blank=True, choices=[('Muito importante', 'muito'), ('Importante', 'medio'), ('Pouco importante', 'pouco'), ('Nada importante', 'nada')], max_length=20, null=True),
        ),
    ]
