# Generated by Django 5.1.5 on 2025-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_customuser_formacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoguide',
            name='licenca',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
