# Generated by Django 5.1.5 on 2025-02-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_alter_userpreference_importancia_sustentabilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='importancia_sustentabilidade',
            field=models.CharField(blank=True, choices=[('muito', 'Muito importante'), ('medio', 'Importante'), ('pouco', 'Pouco importante'), ('nada', 'Nada importante')], max_length=20, null=True),
        ),
    ]
