# Generated by Django 5.1.5 on 2025-02-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_userpreference_importancia_sustentabilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencecategory',
            name='real_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
