# Generated by Django 5.1.5 on 2025-01-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_ecoguide_licenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoguide',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
