# Generated by Django 5.1.5 on 2025-03-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_preferencecategory_real_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='prioridade_viagem',
        ),
        migrations.AlterField(
            model_name='preferencecategory',
            name='category',
            field=models.CharField(choices=[('ecotrip_style', 'Estilo Ecotrip'), ('travel_companion', 'Companheiro de Viagem')], max_length=20, null=True),
        ),
    ]
