# Generated by Django 5.1.5 on 2025-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_ecoguide_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_guide',
        ),
        migrations.AlterField(
            model_name='ecoguide',
            name='licenca',
            field=models.CharField(max_length=15),
        ),
    ]
