# Generated by Django 5.1.5 on 2025-03-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_userpreference_prioridade_viagem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencecategory',
            name='real_name',
        ),
    ]
