# Generated by Django 5.1.5 on 2025-02-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_remove_customuser_is_guide_alter_ecoguide_licenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='users/'),
        ),
    ]
